CATALOGO = [
    {"id": 1, "nombre": "Bulbasaur", "tipo1": "Planta", "tipo2": "Veneno", "hp": 45, "ataque": 49, "defensa": 49, "velocidad": 45, "generacion": 1},
    {"id": 2, "nombre": "Ivysaur", "tipo1": "Planta", "tipo2": "Veneno", "hp": 60, "ataque": 62, "defensa": 63, "velocidad": 60, "generacion": 1},
    {"id": 3, "nombre": "Venusaur", "tipo1": "Planta", "tipo2": "Veneno", "hp": 80, "ataque": 82, "defensa": 83, "velocidad": 80, "generacion": 1},
    {"id": 4, "nombre": "Charmander", "tipo1": "Fuego", "tipo2": "", "hp": 39, "ataque": 52, "defensa": 43, "velocidad": 65, "generacion": 1},
    {"id": 5, "nombre": "Charmeleon", "tipo1": "Fuego", "tipo2": "", "hp": 58, "ataque": 64, "defensa": 58, "velocidad": 80, "generacion": 1},
    {"id": 6, "nombre": "Charizard", "tipo1": "Fuego", "tipo2": "Volador", "hp": 78, "ataque": 84, "defensa": 78, "velocidad": 100, "generacion": 1},
    {"id": 7, "nombre": "Squirtle", "tipo1": "Agua", "tipo2": "", "hp": 44, "ataque": 48, "defensa": 65, "velocidad": 43, "generacion": 1},
    {"id": 8, "nombre": "Wartortle", "tipo1": "Agua", "tipo2": "", "hp": 59, "ataque": 63, "defensa": 80, "velocidad": 58, "generacion": 1},
    {"id": 9, "nombre": "Blastoise", "tipo1": "Agua", "tipo2": "", "hp": 79, "ataque": 83, "defensa": 100, "velocidad": 78, "generacion": 1},
    {"id": 10, "nombre": "Caterpie", "tipo1": "Bicho", "tipo2": "", "hp": 45, "ataque": 30, "defensa": 35, "velocidad": 45, "generacion": 1},
    {"id": 11, "nombre": "Metapod", "tipo1": "Bicho", "tipo2": "", "hp": 50, "ataque": 20, "defensa": 55, "velocidad": 30, "generacion": 1},
    {"id": 12, "nombre": "Butterfree", "tipo1": "Bicho", "tipo2": "Volador", "hp": 60, "ataque": 45, "defensa": 50, "velocidad": 70, "generacion": 1},
    {"id": 16, "nombre": "Pidgey", "tipo1": "Normal", "tipo2": "Volador", "hp": 40, "ataque": 45, "defensa": 40, "velocidad": 56, "generacion": 1},
    {"id": 17, "nombre": "Pidgeotto", "tipo1": "Normal", "tipo2": "Volador", "hp": 63, "ataque": 60, "defensa": 55, "velocidad": 71, "generacion": 1},
    {"id": 18, "nombre": "Pidgeot", "tipo1": "Normal", "tipo2": "Volador", "hp": 83, "ataque": 80, "defensa": 75, "velocidad": 101, "generacion": 1},
    {"id": 19, "nombre": "Rattata", "tipo1": "Normal", "tipo2": "", "hp": 30, "ataque": 56, "defensa": 35, "velocidad": 72, "generacion": 1},
    {"id": 20, "nombre": "Raticate", "tipo1": "Normal", "tipo2": "", "hp": 55, "ataque": 81, "defensa": 60, "velocidad": 97, "generacion": 1},
    {"id": 25, "nombre": "Pikachu", "tipo1": "Electrico", "tipo2": "", "hp": 35, "ataque": 55, "defensa": 40, "velocidad": 90, "generacion": 1},
    {"id": 26, "nombre": "Raichu", "tipo1": "Electrico", "tipo2": "", "hp": 60, "ataque": 90, "defensa": 55, "velocidad": 110, "generacion": 1},
    {"id": 35, "nombre": "Clefairy", "tipo1": "Hada", "tipo2": "", "hp": 70, "ataque": 45, "defensa": 48, "velocidad": 35, "generacion": 1},
    {"id": 36, "nombre": "Clefable", "tipo1": "Hada", "tipo2": "", "hp": 95, "ataque": 70, "defensa": 73, "velocidad": 60, "generacion": 1},
    {"id": 37, "nombre": "Vulpix", "tipo1": "Fuego", "tipo2": "", "hp": 38, "ataque": 41, "defensa": 40, "velocidad": 65, "generacion": 1},
    {"id": 38, "nombre": "Ninetales", "tipo1": "Fuego", "tipo2": "", "hp": 73, "ataque": 76, "defensa": 75, "velocidad": 100, "generacion": 1},
    {"id": 43, "nombre": "Oddish", "tipo1": "Planta", "tipo2": "Veneno", "hp": 45, "ataque": 50, "defensa": 55, "velocidad": 30, "generacion": 1},
    {"id": 44, "nombre": "Gloom", "tipo1": "Planta", "tipo2": "Veneno", "hp": 60, "ataque": 65, "defensa": 70, "velocidad": 40, "generacion": 1},
    {"id": 45, "nombre": "Vileplume", "tipo1": "Planta", "tipo2": "Veneno", "hp": 75, "ataque": 80, "defensa": 85, "velocidad": 50, "generacion": 1},
    {"id": 58, "nombre": "Growlithe", "tipo1": "Fuego", "tipo2": "", "hp": 55, "ataque": 70, "defensa": 45, "velocidad": 60, "generacion": 1},
    {"id": 59, "nombre": "Arcanine", "tipo1": "Fuego", "tipo2": "", "hp": 90, "ataque": 110, "defensa": 80, "velocidad": 95, "generacion": 1},
    {"id": 63, "nombre": "Abra", "tipo1": "Psiquico", "tipo2": "", "hp": 25, "ataque": 20, "defensa": 15, "velocidad": 90, "generacion": 1},
    {"id": 64, "nombre": "Kadabra", "tipo1": "Psiquico", "tipo2": "", "hp": 40, "ataque": 35, "defensa": 30, "velocidad": 105, "generacion": 1},
    {"id": 65, "nombre": "Alakazam", "tipo1": "Psiquico", "tipo2": "", "hp": 55, "ataque": 50, "defensa": 45, "velocidad": 120, "generacion": 1},
    {"id": 66, "nombre": "Machop", "tipo1": "Lucha", "tipo2": "", "hp": 70, "ataque": 80, "defensa": 50, "velocidad": 35, "generacion": 1},
    {"id": 67, "nombre": "Machoke", "tipo1": "Lucha", "tipo2": "", "hp": 80, "ataque": 100, "defensa": 70, "velocidad": 45, "generacion": 1},
    {"id": 68, "nombre": "Machamp", "tipo1": "Lucha", "tipo2": "", "hp": 90, "ataque": 130, "defensa": 80, "velocidad": 55, "generacion": 1},
    {"id": 74, "nombre": "Geodude", "tipo1": "Roca", "tipo2": "Tierra", "hp": 40, "ataque": 80, "defensa": 100, "velocidad": 20, "generacion": 1},
    {"id": 75, "nombre": "Graveler", "tipo1": "Roca", "tipo2": "Tierra", "hp": 55, "ataque": 95, "defensa": 115, "velocidad": 35, "generacion": 1},
    {"id": 76, "nombre": "Golem", "tipo1": "Roca", "tipo2": "Tierra", "hp": 80, "ataque": 120, "defensa": 130, "velocidad": 45, "generacion": 1},
    {"id": 81, "nombre": "Magnemite", "tipo1": "Electrico", "tipo2": "Acero", "hp": 25, "ataque": 35, "defensa": 70, "velocidad": 45, "generacion": 1},
    {"id": 82, "nombre": "Magneton", "tipo1": "Electrico", "tipo2": "Acero", "hp": 50, "ataque": 60, "defensa": 95, "velocidad": 70, "generacion": 1},
    {"id": 92, "nombre": "Gastly", "tipo1": "Fantasma", "tipo2": "Veneno", "hp": 30, "ataque": 35, "defensa": 30, "velocidad": 80, "generacion": 1},
    {"id": 93, "nombre": "Haunter", "tipo1": "Fantasma", "tipo2": "Veneno", "hp": 45, "ataque": 50, "defensa": 45, "velocidad": 95, "generacion": 1},
    {"id": 94, "nombre": "Gengar", "tipo1": "Fantasma", "tipo2": "Veneno", "hp": 60, "ataque": 65, "defensa": 60, "velocidad": 110, "generacion": 1},
    {"id": 95, "nombre": "Onix", "tipo1": "Roca", "tipo2": "Tierra", "hp": 35, "ataque": 45, "defensa": 160, "velocidad": 70, "generacion": 1},
    {"id": 129, "nombre": "Magikarp", "tipo1": "Agua", "tipo2": "", "hp": 20, "ataque": 10, "defensa": 55, "velocidad": 80, "generacion": 1},
    {"id": 130, "nombre": "Gyarados", "tipo1": "Agua", "tipo2": "Volador", "hp": 95, "ataque": 125, "defensa": 79, "velocidad": 81, "generacion": 1},
    {"id": 133, "nombre": "Eevee", "tipo1": "Normal", "tipo2": "", "hp": 55, "ataque": 55, "defensa": 50, "velocidad": 55, "generacion": 1},
    {"id": 134, "nombre": "Vaporeon", "tipo1": "Agua", "tipo2": "", "hp": 130, "ataque": 65, "defensa": 60, "velocidad": 65, "generacion": 1},
    {"id": 135, "nombre": "Jolteon", "tipo1": "Electrico", "tipo2": "", "hp": 65, "ataque": 65, "defensa": 60, "velocidad": 130, "generacion": 1},
    {"id": 136, "nombre": "Flareon", "tipo1": "Fuego", "tipo2": "", "hp": 65, "ataque": 130, "defensa": 60, "velocidad": 65, "generacion": 1},
    {"id": 137, "nombre": "Porygon", "tipo1": "Normal", "tipo2": "", "hp": 65, "ataque": 60, "defensa": 70, "velocidad": 40, "generacion": 1},
    {"id": 147, "nombre": "Dratini", "tipo1": "Dragon", "tipo2": "", "hp": 41, "ataque": 64, "defensa": 45, "velocidad": 50, "generacion": 1},
    {"id": 148, "nombre": "Dragonair", "tipo1": "Dragon", "tipo2": "", "hp": 61, "ataque": 84, "defensa": 65, "velocidad": 70, "generacion": 1},
    {"id": 149, "nombre": "Dragonite", "tipo1": "Dragon", "tipo2": "Volador", "hp": 91, "ataque": 134, "defensa": 95, "velocidad": 80, "generacion": 1},
    {"id": 150, "nombre": "Mewtwo", "tipo1": "Psiquico", "tipo2": "", "hp": 106, "ataque": 110, "defensa": 90, "velocidad": 130, "generacion": 1},
    {"id": 151, "nombre": "Mew", "tipo1": "Psiquico", "tipo2": "", "hp": 100, "ataque": 100, "defensa": 100, "velocidad": 100, "generacion": 1},
    {"id": 152, "nombre": "Chikorita", "tipo1": "Planta", "tipo2": "", "hp": 45, "ataque": 49, "defensa": 65, "velocidad": 45, "generacion": 2},
    {"id": 153, "nombre": "Bayleef", "tipo1": "Planta", "tipo2": "", "hp": 60, "ataque": 62, "defensa": 80, "velocidad": 60, "generacion": 2},
    {"id": 154, "nombre": "Meganium", "tipo1": "Planta", "tipo2": "", "hp": 80, "ataque": 82, "defensa": 100, "velocidad": 80, "generacion": 2},
    {"id": 155, "nombre": "Cyndaquil", "tipo1": "Fuego", "tipo2": "", "hp": 39, "ataque": 52, "defensa": 43, "velocidad": 65, "generacion": 2},
    {"id": 156, "nombre": "Quilava", "tipo1": "Fuego", "tipo2": "", "hp": 58, "ataque": 64, "defensa": 58, "velocidad": 80, "generacion": 2},
    {"id": 157, "nombre": "Typhlosion", "tipo1": "Fuego", "tipo2": "", "hp": 78, "ataque": 84, "defensa": 78, "velocidad": 100, "generacion": 2},
    {"id": 172, "nombre": "Pichu", "tipo1": "Electrico", "tipo2": "", "hp": 20, "ataque": 40, "defensa": 15, "velocidad": 60, "generacion": 2},
    {"id": 175, "nombre": "Togepi", "tipo1": "Hada", "tipo2": "", "hp": 35, "ataque": 20, "defensa": 65, "velocidad": 20, "generacion": 2},
    {"id": 176, "nombre": "Togetic", "tipo1": "Hada", "tipo2": "Volador", "hp": 55, "ataque": 40, "defensa": 85, "velocidad": 40, "generacion": 2},
    {"id": 179, "nombre": "Mareep", "tipo1": "Electrico", "tipo2": "", "hp": 55, "ataque": 40, "defensa": 40, "velocidad": 35, "generacion": 2},
    {"id": 180, "nombre": "Flaaffy", "tipo1": "Electrico", "tipo2": "", "hp": 70, "ataque": 55, "defensa": 55, "velocidad": 45, "generacion": 2},
    {"id": 181, "nombre": "Ampharos", "tipo1": "Electrico", "tipo2": "", "hp": 90, "ataque": 75, "defensa": 85, "velocidad": 55, "generacion": 2},
    {"id": 246, "nombre": "Larvitar", "tipo1": "Roca", "tipo2": "Tierra", "hp": 50, "ataque": 64, "defensa": 50, "velocidad": 41, "generacion": 2},
    {"id": 247, "nombre": "Pupitar", "tipo1": "Roca", "tipo2": "Tierra", "hp": 70, "ataque": 84, "defensa": 70, "velocidad": 51, "generacion": 2},
    {"id": 248, "nombre": "Tyranitar", "tipo1": "Roca", "tipo2": "Siniestro", "hp": 100, "ataque": 134, "defensa": 110, "velocidad": 61, "generacion": 2},
]

def listar_catalogo():
    for item in CATALOGO:
        print(f"{item['id']:>3}  {item['nombre']}")
        # Ejemplo de lo que imprime: 1 Bulbasaur (...) 248 Tyranitar
